print("##############################")
print("#                            #")
print("#   M. Irfan Madani Wahidun  #")
print("#        2610817110023       #")
print("#                            #")
print("##############################")